#!/bin/bash
#SBATCH --job-name=walloss
#SBATCH --output=${HOME}/task_logs/%j.log
#SBATCH --partition=h100
#SBATCH --qos=vita
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-node=4
#SBATCH --nodes=1
#SBATCH --time=24:00:00
#SBATCH --mem=200G

# 5 epoch can give 100% training success rate!

accelerate launch \
    --multi_gpu \
    --num_processes=4 \
    --mixed_precision="bf16" \
    /work/vita/lanfeng/vlas/vla/gwm_wiser/scripts/lerobot_train.py \
    --dataset.repo_id="unused" \
    --dataset.root="/work/vita/lanfeng/vlas/vla/wiser_dataset" \
    --policy.type=wall_x \
    --output_dir=/work/vita/lanfeng/vlas/exp_results/ \
    --job_name="walloss_wiser" \
    --policy.repo_id="unused" \
    --policy.push_to_hub=false \
    --policy.pretrained_name_or_path=x-square-robot/wall-oss-flow \
    --policy.prediction_mode=diffusion \
    --policy.attn_implementation=eager \
    --policy.n_action_steps=20 \
    --policy.chunk_size=20 \
    --wandb.enable=true \
    --eval_rounds=1 \
    --eval_interval=5 \
    --total_learning_epoches=10 \
    --batch_size=6
