#!/bin/bash
#SBATCH --job-name=gwm_ac
#SBATCH --output=${HOME}/task_logs/%j.log
#SBATCH --partition=h100
#SBATCH --qos=vita
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=64
#SBATCH --gpus-per-node=4
#SBATCH --nodes=3
#SBATCH --time=24:00:00
#SBATCH --mem=200G

export MASTER_ADDR=$(scontrol show hostnames $SLURM_JOB_NODELIST | head -n 1)
export MASTER_PORT=29500

srun torchrun \
    --nnodes=3 \
    --nproc_per_node=4 \
    --rdzv_id=$SLURM_JOB_ID \
    --rdzv_backend=c10d \
    --rdzv_endpoint=$MASTER_ADDR:$MASTER_PORT \
    /work/vita/lanfeng/vlas/vla/gwm_wiser/scripts/gwm_train.py \
    --dataset.repo_id="unused" \
    --dataset.root="/work/vita/lanfeng/vlas/vla/wiser_dataset" \
    --output_dir=/work/vita/lanfeng/vlas/exp_results/ \
    --job_name="gwm_ac_3_epoch" \
    --wandb.enable=true \
    --eval_interval=1 \
    --embedder_model_path="/work/vita/lanfeng/vlas/Qwen3-VL-Embedding-8B" \
    --total_learning_epoches=3 \
    --batch_size=32 \
    --use_compile=false \
    --num_workers=4 \
    --action_conditioned=true
