"""The robot model GWM renders, derived from the one the planner plans with.

GWM scores a candidate from robot-only renders of it, so the rendered robot has
to be the robot that will move. Two things stand between the planning model and
SAPIEN.

**The gripper.** `real_data_train/renderer/assets.py` welds a Robotiq **2F-85**;
this rig carries a **2F-140**, whose fingertip plane sits 62 mm further from the
flange. Rendering a 2F-85 would put the gripper 62 mm short in every RAT frame
and fail the overlay gate outright. So the render model is
`gwm_hardware/assets/panda_robotiq_2f_140.urdf` -- the same file cuRobo and
cuTAMP plan with, single-sourced from `common/build_2f140.py`.

**The inertias.** SAPIEN's URDF loader asserts that every inertia tensor is
positive definite. cuTAMP's `panda_robotiq_2f_85.urdf`, which our arm half is
reused from verbatim, ships a `panda_link3` whose tensor has eigenvalues
`[-0.0038, +0.0033, +0.0217]` -- negative, i.e. not a physical rigid body.
cuRobo never looks (it needs kinematics and collision spheres), so the planning
model is unaffected and stays untouched; SAPIEN refuses to load the file.

This module writes a RENDER-ONLY copy with such tensors repaired. The repair is
allowed to be crude -- the renderer sets qpos directly and never steps physics,
so inertia has no effect on a single pixel -- but it is logged rather than done
quietly, because a model that differs from the planning model is exactly the
kind of thing that should never be invisible. Geometry, joints, limits, mimics
and mesh paths are copied through untouched; only `<inertia>` is rewritten.

    python -m gwm_hardware.gwm_arm.render_model            # build + report
    python -m gwm_hardware.gwm_arm.render_model --preview out.png
"""

import argparse
import logging
import xml.etree.ElementTree as ET
from pathlib import Path

import numpy as np

from gwm_hardware.common.paths import ASSETS

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
_log = logging.getLogger("gwm_arm.render_model")

PLANNING_URDF = ASSETS / "panda_robotiq_2f_140.urdf"
RENDER_URDF = ASSETS / "panda_robotiq_2f_140_render.urdf"


def _repair_inertia(link: ET.Element) -> str | None:
    """Make one link's inertia positive definite. Returns a note if it changed."""
    inertial = link.find("inertial")
    if inertial is None:
        return None  # SAPIEN fills a default for a link with no inertial at all
    mass_el = inertial.find("mass")
    inertia = inertial.find("inertia")
    if inertia is None:
        return None
    mass = float(mass_el.get("value")) if mass_el is not None else 0.0
    keys = ("ixx", "ixy", "ixz", "iyy", "iyz", "izz")
    ixx, ixy, ixz, iyy, iyz, izz = (float(inertia.get(k, 0.0)) for k in keys)
    I = np.array([[ixx, ixy, ixz], [ixy, iyy, iyz], [ixz, iyz, izz]])
    eig = np.linalg.eigvalsh(I)
    if mass > 0 and (eig > 0).all():
        return None

    # Rebuild as a diagonal tensor from the magnitudes of the original
    # eigenvalues: it keeps the tensor's scale (so nothing downstream sees an
    # absurd body) while guaranteeing positive definiteness.
    floor = max(np.abs(eig).max() * 1e-3, 1e-9)
    d = np.maximum(np.abs(eig), floor)
    for k, v in zip(("ixx", "iyy", "izz"), d):
        inertia.set(k, f"{v:.9g}")
    for k in ("ixy", "ixz", "iyz"):
        inertia.set(k, "0")
    if mass <= 0 and mass_el is not None:
        mass_el.set("value", "0.001")
    return (f"{link.get('name')}: eigenvalues {np.round(eig, 6).tolist()} -> "
            f"diagonal {np.round(d, 6).tolist()}")


def build_render_urdf(src: Path = PLANNING_URDF, dst: Path = RENDER_URDF) -> Path:
    if not src.exists():
        raise SystemExit(
            f"{src} missing. Generate the planning model first:\n"
            "  pixi run --manifest-path droid/tiptop/pixi.toml "
            "python -m gwm_hardware.common.build_2f140"
        )
    tree = ET.parse(src)
    root = tree.getroot()
    notes = [n for n in (_repair_inertia(l) for l in root.findall("link")) if n]
    # XML comments cannot contain a double hyphen, so no em-dashes in here.
    comment = ET.Comment(
        " RENDER ONLY. Generated by gwm_hardware.gwm_arm.render_model from "
        f"{src.name}. Inertias repaired for SAPIEN's positive-definite check; "
        "the planner uses the source file. Do not plan with this. Repaired: "
        + ("; ".join(notes) if notes else "none").replace("--", "-") + " ")
    root.insert(0, comment)
    dst.parent.mkdir(parents=True, exist_ok=True)
    tree.write(dst, encoding="utf-8", xml_declaration=True)
    for n in notes:
        _log.info(f"repaired inertia -- {n}")
    _log.info(f"render URDF -> {dst}  ({len(notes)} link(s) repaired)")
    return dst


def ensure_render_urdf() -> Path:
    """Build if missing or older than the planning model."""
    if not RENDER_URDF.exists() or RENDER_URDF.stat().st_mtime < PLANNING_URDF.stat().st_mtime:
        return build_render_urdf()
    return RENDER_URDF


def look_at(eye: np.ndarray, target: np.ndarray, up=(0.0, 0.0, 1.0)) -> np.ndarray:
    """CV-axis cam2world (x right, y down, z forward) looking from eye at target.

    This is the convention `FrankaRobotRenderer.render` consumes despite its
    `cam2world_gl` parameter name, and the same one the h5
    `pos_w`/`quat_w_ros` pair encodes.
    """
    f = np.asarray(target, float) - np.asarray(eye, float)
    f /= np.linalg.norm(f)
    r = np.cross(f, np.asarray(up, float))
    r /= np.linalg.norm(r)
    d = np.cross(f, r)
    m = np.eye(4)
    m[:3, 0], m[:3, 1], m[:3, 2] = r, d, f
    m[:3, 3] = eye
    return m


def preview(out: Path, q: np.ndarray | None = None) -> None:
    """Render open and closed at one pose, side by side, as a smoke test."""
    from PIL import Image
    from real_data_train.renderer.franka_renderer import FrankaRobotRenderer, parse_mimic_chain

    urdf = ensure_render_urdf()
    _log.info(f"mimic chain: {parse_mimic_chain(urdf)}")
    r = FrankaRobotRenderer(str(urdf), arm="panda")
    if q is None:  # the rig's capture pose
        q = np.array([-0.2099, -0.1645, 0.1760, -1.3773, 0.0306, 1.2154, -0.0256])
    K = np.array([[900.0, 0, 640.0], [0, 900.0, 360.0], [0, 0, 1.0]])
    # Aimed at the gripper: at the capture pose the TCP sits ~0.55 m up,
    # and a preview that misses the fingers checks nothing.
    c2w = look_at(eye=np.array([0.75, 1.0, 1.0]), target=np.array([0.42, 0.0, 0.62]))
    frames = r.render(np.repeat(q[None], 2, 0), np.array([0.0, 1.0]), K, c2w, 1280, 720)
    cov = (frames.reshape(2, -1, 3).any(-1)).mean(axis=1)
    _log.info(f"robot pixel coverage: open {cov[0]:.2%}, closed {cov[1]:.2%}")
    Image.fromarray(np.concatenate(list(frames), axis=1)).save(out)
    _log.info(f"preview -> {out}")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--src", type=Path, default=PLANNING_URDF)
    ap.add_argument("--dst", type=Path, default=RENDER_URDF)
    ap.add_argument("--preview", type=Path, help="also render a smoke frame here")
    args = ap.parse_args()
    build_render_urdf(args.src, args.dst)
    if args.preview:
        preview(args.preview)


if __name__ == "__main__":
    main()
