name: "fruit"

train:
  cube_colors:
    - red
    - yellow
    - green
    - blue

  table_images:
    - path: "4_fruit/train_apple.png"
    - path: "4_fruit/train_banana.png"
    - path: "4_fruit/train_orange.png"

  task_referring_expressions:
    - ["red cube", "the image of an apple"]
    - ["the first cube from the left", "the image of a yellow curved fruit"]
    - ["red cube", "the image of an orange"]
    - ["the second cube from the left", "the image of a red and delicious fruit"]
    - ["yellow cube", "the image of a banana"]
    - ["the cube to the right of the red cube", "the image of a round citrus fruit"]
    - ["green cube", "the image of an apple"]
    - ["the second cube from the right", "the image of a yellow curved fruit"]
    - ["green cube", "the image of an orange"]
    - ["the cube on the far right", "the image of a red and delicious fruit"]
    - ["blue cube", "the image of a banana"]
    - ["the rightmost cube", "the image of a round citrus fruit"]

test:
  cube_colors:
    - purple
    - grey
    - orange
    - cyan

  table_images:
    - path: "4_fruit/test_grape.png"
    - path: "4_fruit/test_pineapple.png"
    - path: "4_fruit/test_strawberry.png"

  task_referring_expressions:
    - ["purple cube", "the image of grapes"]
    - ["the cube at position one from the left", "the image of a tropical fruit with spiky leaves"]
    - ["purple cube", "the image of a strawberry"]
    - ["the cube sandwiched between purple and orange", "the image of a bunch of small purple fruit"]
    - ["grey cube", "the image of a pineapple"]
    - ["the cube immediately next to the purple one", "the image of a red berry with seeds on the outside"]
    - ["orange cube", "the image of grapes"]
    - ["the cube on the left side of cyan", "the image of a tropical fruit with spiky leaves"]
    - ["orange cube", "the image of a strawberry"]
    - ["the cube to the right of the orange cube", "the image of a bunch of small purple fruit"]
    - ["cyan cube", "the image of a pineapple"]
    - ["the cube on the most right side", "the image of a red berry with seeds on the outside"]
