"""Panda + Robotiq 2F-140 robot model, exposed with cuTAMP's API shape.

`cutamp.robots.franka_robotiq` hard-codes `panda_robotiq_2f_85.yml`, and this
rig carries a 2F-140. Rather than fork cuTAMP (G-4/G-7) or patch `tiptop/`
(G-18), this module mirrors that module's public surface against the config
generated by `build_2f140.py` + `build_2f140_cfg.py`, talking straight to
cuRobo. Anything that takes a cuTAMP loader can therefore take one of these:

    cutamp.robots.franka_robotiq          gwm_hardware.robot_2f140
    -------------------------------------------------------------------
    panda_robotiq_curobo_cfg()            curobo_cfg()
    get_panda_robotiq_kinematics_model()  get_kinematics_model()
    get_panda_robotiq_ik_solver(world)    get_ik_solver(world)
    get_panda_robotiq_gripper_spheres()   get_gripper_spheres()
    panda_robotiq_neutral_joint_positions NEUTRAL_JOINT_POSITIONS

Regenerate the assets after any cuTAMP reinstall (the clone they are derived
from is gitignored):

    python -m gwm_hardware.build_2f140 && python -m gwm_hardware.build_2f140_cfg
"""

import logging
from pathlib import Path

import torch
from jaxtyping import Float

from curobo.cuda_robot_model.cuda_robot_model import CudaRobotModel
from curobo.geom.types import WorldConfig
from curobo.types.base import TensorDeviceType
from curobo.types.robot import RobotConfig
from curobo.util_file import load_yaml
from curobo.wrap.reacher.ik_solver import IKSolver, IKSolverConfig

_log = logging.getLogger(__name__)

ASSETS_DIR = Path(__file__).resolve().parent / "assets"
CFG_PATH = ASSETS_DIR / "panda_robotiq_2f_140.yml"

# Same arm, so the same neutral pose cuTAMP uses for the 2F-85 Panda.
NEUTRAL_JOINT_POSITIONS = (0.0, -0.628, 0.0, -2.513, 0.0, 1.885, 0.0)

DRIVER_JOINT = "finger_joint"
# Driver limits from the 2F-140 xacro: 0 = fully open, 0.7 = fully closed.
DRIVER_OPEN = 0.0
DRIVER_CLOSED = 0.7


def _require_assets() -> None:
    if not CFG_PATH.exists():
        raise FileNotFoundError(
            f"{CFG_PATH} not found. Generate it with:\n"
            "  python -m gwm_hardware.build_2f140\n"
            "  python -m gwm_hardware.build_2f140_cfg"
        )


def curobo_cfg() -> dict:
    """Full cuRobo config dict, with asset paths pinned to our tree."""
    _require_assets()
    cfg = load_yaml(str(CFG_PATH))
    kinematics = cfg["robot_cfg"]["kinematics"]
    for key in ("external_asset_path", "external_robot_configs_path"):
        kinematics.setdefault(key, str(ASSETS_DIR))
    return cfg


def _cfg_dict() -> dict:
    return curobo_cfg()["robot_cfg"]


def get_robot_config() -> RobotConfig:
    return RobotConfig.from_dict(_cfg_dict())


def get_kinematics_model() -> CudaRobotModel:
    """cuRobo kinematics model for the Panda + 2F-140."""
    return CudaRobotModel(get_robot_config().kinematics)


def get_ik_solver(
    world_cfg: WorldConfig,
    num_seeds: int = 12,
    self_collision_opt: bool = False,
    self_collision_check: bool = True,
    use_particle_opt: bool = False,
) -> IKSolver:
    """cuRobo IK solver, same knobs as cuTAMP's Panda + 2F-85 solver."""
    ik_config = IKSolverConfig.load_from_robot_config(
        get_robot_config(),
        world_cfg,
        num_seeds=num_seeds,
        self_collision_opt=self_collision_opt,
        self_collision_check=self_collision_check,
        use_particle_opt=use_particle_opt,
    )
    return IKSolver(ik_config)


def get_gripper_spheres(
    tensor_args: TensorDeviceType = TensorDeviceType(),
) -> Float[torch.Tensor, "num_spheres 4"]:
    """Gripper collision spheres in the gripper frame, closing axis on y.

    Mirrors `cutamp.robots.utils.get_robotiq_2f_85_gripper_spheres`, which
    cuTAMP uses to reject candidate grasps that collide with the target object
    (`particle_initialization.py:154`). Frame convention is cuTAMP's: **origin
    frame with z-up**, not the conventional z-down gripper frame.

    Generated by `build_2f140_cfg.build_gripper_spheres`, whose derivation is
    calibrated against cuTAMP's shipped 2F-85 set before it is trusted here.

    Two deliberate differences from the 2F-85 reference, both worth watching on
    the first real grasps:

    - 287 spheres vs the reference's 23. The reference is hand-authored; this
      is derived from the per-link collision fit.
    - It is genuinely three-dimensional (x spans +-38 mm), where the 2F-85's
      bare gripper happens to lie flat on the closing plane. That makes this
      filter strictly more conservative -- it can reject grasps the 2F-85
      pipeline would have kept.
    """
    path = ASSETS_DIR / "panda_robotiq_2f_140_gripper_spheres.pt"
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found. Generate it with:\n"
            "  python -m gwm_hardware.build_2f140_cfg"
        )
    spheres = torch.load(path, map_location=tensor_args.device, weights_only=True)
    assert spheres.ndim == 2 and spheres.shape[1] == 4, f"bad shape {spheres.shape}"
    return spheres[spheres[:, 3] > 0]


def gripper_qpos(fraction_closed: float) -> float:
    """Driver joint angle for a 0 (open) .. 1 (closed) command."""
    f = min(max(float(fraction_closed), 0.0), 1.0)
    return DRIVER_OPEN + f * (DRIVER_CLOSED - DRIVER_OPEN)
